// DictComp.idl : IDL source for DictComp.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DictComp.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
[
    object,
    uuid(001A7733-AD05-4009-BF22-798BA9D52036),    
    helpstring("IDictionary Interface"),
    pointer_default(unique)
]
interface IDictionary : IUnknown
{
    [helpstring("method Initialize")] HRESULT Initialize(void);
    [helpstring("method LoadLibrary")] HRESULT LoadLibrary(LPOLESTR);
    [helpstring("method InsertWord")] HRESULT InsertWord(LPOLESTR, LPOLESTR);
    [helpstring("method DeleteWord")] HRESULT DeleteWord(LPOLESTR);
    [helpstring("method LookupWord")] HRESULT LookupWord(LPOLESTR, LPOLESTR*);
    [helpstring("method RestoreLibrary")] HRESULT RestoreLibrary(LPOLESTR);
    [helpstring("method FreeLibrary")] HRESULT FreeLibrary(void);
};

[
    object,
    uuid(20A839D6-125D-43a4-BA89-09DB6769DDD9),    
    helpstring("ISpellCheck Interface"),
    pointer_default(unique)
]
interface ISpellCheck : IUnknown
{
		[helpstring("method CheckWord")] HRESULT CheckWord(LPOLESTR, LPOLESTR*);
};



[
	uuid(AAF161AC-2BC3-40F1-93F7-D2252A88B00D),
	version(1.0),
	helpstring("DictComp 1.0 Type Library")
]
library DICTCOMPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(ACA2CA2A-0968-4b89-89F0-54072C2551F7),
		helpstring("Dictionary Class")
	]
	coclass CComDictionary
	{
		[default] interface IDictionary;
	};
};
